version: "3"
services:
  front-end:
    container_name: pic-frontend
    image: picture
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
  server:
    container_name: pic-server
    image: pic_server
    environment:
      - BACKEND_HOST=server
    volumes:
      - /Users/vbojilova/Projects/pictcr_viz/data:/data/
    ports:
      - "5000:5000"
    depends_on:
      - redis
      #volumes:
      #  - /mnt/redis:/data
